{% set version = '2.1-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ssc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ssc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ssc/ssc_{{ version }}.tar.gz
  sha256: bc298b7b954fece3e1e6be85d95a9a0ad65626082801208a22cfc905d10d07d3

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-proxy
  run:
    - r-base
    - r-proxy

test:
  commands:
    - $R -e "library('ssc')"           # [not win]
    - "\"%R%\" -e \"library('ssc')\""  # [win]

about:
  home: https://github.com/mabelc/SSC
  license: GPL-3.0-or-later
  summary: Provides a collection of self-labeled techniques for semi-supervised classification.
    In semi-supervised classification, both labeled and unlabeled data are used to train
    a classifier. This learning paradigm has obtained promising results, specifically
    in the presence of a reduced set of labeled examples. This package implements a
    collection of self-labeled techniques to construct a classification model. This
    family of techniques enlarges the original labeled set using the most confident
    predictions to classify unlabeled data. The techniques implemented can be applied
    to classification problems in several domains by the specification of a supervised
    base classifier. At low ratios of labeled data, it can be shown to perform better
    than classical supervised classifiers.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ssc
# Type: Package
# Title: Semi-Supervised Classification Methods
# Version: 2.1-0
# Authors@R: c(person("Mabel", "Gonzalez", role = "aut", email = "mabelc@correo.ugr.es", comment = c(ORCID = "0000-0003-0152-444X")), person("Osmani", "Rosado-Falcon", role = "aut", email = "osmanir@uclv.cu", comment = c(ORCID = "0000-0002-2639-3354")), person("Jose Daniel", "Rodriguez", role = "aut", email = "josedaniel@uclv.cu", comment = c(ORCID = "0000-0002-8489-4106")), person("Christoph", "Bergmeir", role = c("ths", "cre"), email = "c.bergmeir@decsai.ugr.es", comment = c(ORCID = "0000-0002-3665-9021")), person("Isaac", "Triguero", role = "ctb", email = "isaac.triguero@nottingham.ac.uk", comment = c(ORCID = "0000-0002-0150-0651")), person("Jose Manuel", "Benitez", role = "ths", email = "j.m.benitez@decsai.ugr.es", comment = c(ORCID = "0000-0002-2346-0793")) )
# Description: Provides a collection of self-labeled techniques for semi-supervised classification. In semi-supervised classification, both labeled and unlabeled data are used to train a classifier. This learning paradigm has obtained promising results, specifically in the presence of a reduced set of labeled examples. This package implements a collection of self-labeled techniques to construct a classification model. This family of techniques enlarges the original labeled set using the most confident predictions to classify unlabeled data. The techniques implemented can be applied to classification problems in several domains by the specification of a supervised base classifier. At low ratios of labeled data, it can be shown to perform better than classical supervised classifiers.
# Depends: R (>= 3.2.3)
# Imports: stats, proxy
# Suggests: caret, e1071, C50, kernlab, testthat, timeDate, stringi, R.rsp
# VignetteBuilder: R.rsp
# License: GPL (>= 3)
# URL: https://github.com/mabelc/SSC
# BugReports: https://github.com/mabelc/SSC/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2019-12-15 20:56:23 UTC; bergmeir
# Author: Mabel Gonzalez [aut] (<https://orcid.org/0000-0003-0152-444X>), Osmani Rosado-Falcon [aut] (<https://orcid.org/0000-0002-2639-3354>), Jose Daniel Rodriguez [aut] (<https://orcid.org/0000-0002-8489-4106>), Christoph Bergmeir [ths, cre] (<https://orcid.org/0000-0002-3665-9021>), Isaac Triguero [ctb] (<https://orcid.org/0000-0002-0150-0651>), Jose Manuel Benitez [ths] (<https://orcid.org/0000-0002-2346-0793>)
# Maintainer: Christoph Bergmeir <c.bergmeir@decsai.ugr.es>
# Repository: CRAN
# Date/Publication: 2019-12-15 21:30:02 UTC
